
description = "The worldâ€™s fastest framework for building websites"
## Setting this to true will add a "noindex" to *EVERY* page on the site..
removefromexternalsearch = false
## Gh repo for site footer (include trailing slash)
ghrepo = "https://github.com/gohugoio/hugoDocs/"
## GH Repo for filing a new issue
github_repo = "https://github.com/gohugoio/hugo/issues/new"
### Edit content repo (set to automatically enter "edit" mode; this is good for "improve this page" links)
ghdocsrepo = "https://github.com/gohugoio/hugoDocs/tree/master/docs"
## Gitter URL
gitter = "https://gitter.im/spf13/hugo"
## Discuss Forum URL
forum = "https://discourse.gohugo.io/"
## Google Tag Manager
gtmid = ""

# First one is picked as the Twitter card image if not set on page.
images = ["images/gohugoio-card.png"]

flex_box_interior_classes = "flex-auto w-100 lg:w-2/5 mr-3 mb-3 bg-white border-gray-400 leading-normal"

#sidebar_direction = "sidebar_left"