baseURL = "https://example.org"

disableKinds = ["page", "section", "taxonomy", "term"]

[module]
[module.hugoVersion]
extended = false
min = "0.92.0"
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-jslibs-dist/alpinejs/v3"
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-jslibs/turbo/v7"
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-jslibs/instantpage"

